# Generated by Django 2.2.5 on 2019-09-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='s',
            field=models.SlugField(blank=True, default=None, max_length=160, unique=True),
        ),
    ]
