# Generated by Django 2.2.5 on 2019-10-23 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0002_auto_20190917_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institucion',
            old_name='s',
            new_name='slug',
        ),
    ]
