# Generated by Django 2.0.7 on 2019-10-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0003_auto_20191023_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='idEntidad',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='institucion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
