# Generated by Django 2.0.7 on 2019-10-25 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0005_auto_20191024_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscrito',
            name='programas',
        ),
        migrations.AddField(
            model_name='inscrito',
            name='programas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='get_inscritos', to='instituciones.Programa'),
            preserve_default=False,
        ),
    ]
